### ISSUE TITLE
大佬能增加个好友备注功能么

### ISSUE THREAD

**Issue by tw19941212** [xiandanin/github-tags#1]
从git_marks看过来的,关注好友有时确实会忘了当初是为什么关注他的,不过这个功能可能不是很实用吧

**Comment by xiandanin** [comment]
你这个需求也太小众了吧。。。😓

**Comment by tw19941212** [comment]
支持大佬棒棒棒

**Comment by tw19941212** [comment]
刚刚试了一下刷新一下就没了标签也没存入Bmob中

**Comment by xiandanin** [comment]
截个图看下控制台什么错误

不一样的问题不要提到一个issue里面
