### ISSUE TITLE
数据云同步多次都未成功。不知道哪里出了问题

### ISSUE THREAD

**Issue by we11cheng** [xiandanin/github-tags#2]

**Comment by xiandanin** [comment]
打开控制台刷新看有报错吗

**Comment by we11cheng** [comment]
![image](https://user-images.githubusercontent.com/13333981/54912827-6dc08680-4f2c-11e9-9890-a72373583de5.png)

**Comment by xiandanin** [comment]
把SS关了会正常吗

Response截图看一下

**Comment by we11cheng** [comment]
路由器默认搞了ss。而且github还就走的代理。不走ss我得回家试才知道。
![image](https://user-images.githubusercontent.com/13333981/54913471-c3e1f980-4f2d-11e9-8d49-4b608b25e7bc.png)

**Comment by xiandanin** [comment]
你手动在比目云后台建一个`project_tags`表 应该就行了

![image](https://user-images.githubusercontent.com/17588779/54913874-b37e4e80-4f2e-11e9-92d3-7b0f6c045249.png)

下个版本看能不能加上自动建表

**Comment by we11cheng** [comment]
新增的tag可以了。导入旧版json我还没试成功。

**Comment by we11cheng** [comment]
不影响使用。我条目也不多

**Comment by xiandanin** [comment]
[Commit 修复没有自动建表的问题](https://github.com/dengyuhan/github-tags/commit/5e677c645bf7a3aba6c4fe78183a258831e9b9a1)
